Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "vmware_desktop" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = true
  end
  config.vm.define :client1 do |node|
    node.vm.network :private_network, ip: "192.168.30.2"
    node.vm.provision :shell, inline: <<-SHELL
      sudo apt -y update
      sudo apt install net-tools
      ip route add 192.168.232.0/24 via 192.168.30.4
      ip link add vxlan1 type vxlan id 100 dstport 4789 srcport 4789 4790
      ip addr add 192.168.5.2/24 dev vxlan1
      ip link set up vxlan1
      bridge fdb add 00:00:00:00:00:00 dev vxlan1 dst 192.168.232.129
    SHELL
  end

  config.vm.define :natRouter do |node|
    node.vm.network :private_network, ip: "192.168.30.4"
    node.vm.network :private_network, ip: "192.168.232.120"
    node.vm.provision :shell, inline: <<-SHELL
      sudo apt -y update
      sudo apt install net-tools
      sudo apt install iftop
      apt-get install -y iptables
      sudo iptables -t nat -A POSTROUTING -s 192.168.30.0/24 -j MASQUERADE
      sysctl net.ipv4.ip_forward=1
    SHELL
  end

  config.vm.define :client2 do |node|
    node.vm.network :private_network, ip: "192.168.232.126"
    node.vm.provision :shell, inline: <<-SHELL
      sudo apt -y update
      sudo apt install net-tools
      ip link add vxlan1 type vxlan id 100 dstport 4789 srcport 4789 4790
      ip addr add 192.168.5.3/24 dev vxlan1
      ip link set up vxlan1
      bridge fdb add 00:00:00:00:00:00 dev vxlan1 dst 192.168.232.129
    SHELL
  end

end