Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false
  config.vm.provider "virtualbox" do |vb|
      vb.gui = true
  end
  config.vm.define :client1 do |node|
    node.vm.network :private_network, ip: "192.168.30.2"
    node.vm.provision :shell, inline: <<-SHELL
      sudo apt -y update
      sudo apt install net-tools
      ip route add 192.168.40.0/24 via 192.168.30.4
      ip link add vxlan1 type vxlan id 100 dstport 4789 srcport 4789 4790
      ip addr add 192.168.5.2/24 dev vxlan1
      ip link set up vxlan1
      bridge fdb add 00:00:00:00:00:00 dev vxlan1 dst 192.168.40.5
    SHELL
  end

  config.vm.define :client2 do |node|
    node.vm.network :private_network, ip: "192.168.40.6"
    node.vm.provision :shell, inline: <<-SHELL
      sudo apt -y update
      sudo apt install net-tools
      ip link add vxlan1 type vxlan id 200 dstport 4789 srcport 4789 4790
      ip addr add 192.168.5.3/24 dev vxlan1
      ip link set up vxlan1
      bridge fdb add 00:00:00:00:00:00 dev vxlan1 dst 192.168.40.5
    SHELL
  end

  config.vm.define :natRouter do |node|
    node.vm.network :private_network, ip: "192.168.30.4"
    node.vm.network :private_network, ip: "192.168.40.4"
    node.vm.provision :shell, inline: <<-SHELL
      sudo apt -y update
      sudo apt install net-tools
      sudo apt install iftop
      apt-get install -y iptables
      sudo iptables -t nat -A POSTROUTING -s 192.168.30.0/24 -j MASQUERADE
      sysctl net.ipv4.ip_forward=1
    SHELL
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
  config.vm.define :server do |node|
    node.vm.network :private_network, ip: "192.168.40.5"
    node.vm.provision :file, source: "vxlan_hp.py", destination: "vxlan_hp.py"
    node.vm.provision :file, source: "vxlan_hp.c", destination: "vxlan_hp.c"
    node.vm.provision :file, source: "server_vms", destination: "Vagrantfile"
    node.vm.provision :shell, inline: <<-SHELL
      sudo apt -y update
      sudo apt install net-tools
      sudo apt install iftop
      sudo apt-get -y install bpfcc-tools linux-headers-$(uname -r)
      sudo apt -y install python3-pip
      pip3 install pyroute2
      sudo apt -y install openvswitch-switch
      sudo apt -y install virtualbox
      sudo apt -y install vagrant   
      sudo ovs-vsctl add-br br0
      sudo ifconfig br0 up
      sudo ovs-vsctl add-port br0 enp0s8
      sudo ifconfig enp0s8 0
      sudo dhclient br0
      sudo ip tuntap add mode tap vport
      sudo ifconfig vport up
      sudo ovs-vsctl add-port br0 vxlanA -- set interface vxlanA type=vxlan options:remote_ip=192.168.40.4 options:key=100
      sudo ovs-vsctl add-port br0 vxlanB -- set interface vxlanB type=vxlan options:remote_ip=192.168.40.6 options:key=200
    SHELL
  end
end